### ISSUE TITLE
FDAI (101) is 90 deg off

### ISSUE THREAD

**Issue by EricKerman** [Tunefix/KSP_MOCR#11]
When pointing "up" it indicates pointing at the horizon. 

![image](https://user-images.githubusercontent.com/37761292/37871280-fcfc9dfe-2faf-11e8-9215-f47d0de170a3.png)

The DSKY  Verb None program does not input the data so no way to change i.

**Comment by Tunefix** [comment]
The black/white/black-ring is not the horizon on a FDAI. The horizon is where the color goes from white to black. So the FDAI is correct. When getting into orbit you lean right, and follow the black/white/black down from 90° to 0° pitch.

An FDAI (Flight Director/Attitude Indicator) is a different thing from the navball that KSP has. An FDAI can be used in many different ways, depending on what the pilot prefers. And once I get the DSKY/AGC-stuff up and running again, the FDAI offset-angles and target-angles can be altered (again), to set it up to giving the wanted indication.

DSKY is sadly not working in A6, because i am rewriting the entire DKSY/AGC-stuff.
Look out for A7!

**Comment by Tunefix** [comment]
Here is a image of how it looks when nose is pointing at the horizon:
![image](https://user-images.githubusercontent.com/15075682/37876488-3bb6f452-304d-11e8-84dc-4ddd35274890.png)
